#!/bin/sh
REPIDCAN=/db/replicate_id_can
REPIDESP=/db/replicate_id_esp
TIMEOUT=3600 # 1 hora
echo "Content-type:text/html\r\n"
if [ ! -s "$REPIDESP" ]; then
  echo "No existe replica peninsula"
elif [ ! -s "$REPIDCAN" ]; then
  echo "No existe replica Canarias"
elif [ "$(( $(date +"%s") - $(stat -c "%Y" "$REPIDESP") ))" -gt "$TIMEOUT" ]; then
  stat "$REPIDESP"
elif [ "$(( $(date +"%s") - $(stat -c "%Y" "$REPIDCAN") ))" -gt "$TIMEOUT" ]; then
  stat "$REPIDCAN"
else
  echo "Servicio OK"
fi

