#!/bin/sh
CHANGESLOG=/db/changes.log
TIMEOUT=86400 # 1 Dia
echo "Content-type:text/html\r\n"
if [ "$(( $(date +"%s") - $(stat -c "%Y" "$CHANGESLOG") ))" -gt "$TIMEOUT" ]; then
  stat "$CHANGELOG"
else
  echo "Servicio OK"
fi
